id_to_name = {
    "example": "Example",
    "a-fistful-of-cards": "A Fistful of Cards",
    "a-fistful-of-cards-ii": "A Fistful of Cards II",
    "a-fistful-of-cards-iii": "A Fistful of Cards III",
    "a-fistful-of-cards-iv": "A Fistful of Cards IV",
    "aha-erlebnis": "Aha Erlebnis",
    "are-you-sure": "Are You Sure?",
    "balloon-animals": "Balloon Animals",
    "beads": "Beads",
    "bluenos-puzzle-box": "Blueno's Puzzle Box",
    "boring-plot": "Boring Plot",
    "chain-letters": "Chain Letters",
    "color-transfer": "Color Transfer",
    "constellation": "Constellation",
    "cutting-room-floor": "Cutting Room Floor",
    "drop-the": "Drop the...",
    "eye-of-the-storm": "Eye of the Storm",
    "eye-spy": "Eye Spy",
    "eye-to-eye": "Eye-to-Eye",
    "filming-schedule": "Filming Schedule",
    "financial-crimes-3": "Partaking in a Nontrivial Amount of Fraud:  Embezzlement:  and Other Financial Crimes 3",
    "find-ben": "Find Ben",
    "fractal-shanty": "Fractal Shanty",
    "fridge-magnets": "Fridge Magnets",
    "galileo-was-wrong": "Galileo Was Wrong",
    "genetic-counseling": "Genetic Counseling",
    "hand-letters": "Hand Letters",
    "heist": "Heist",
    "heist-ii": "Heist II",
    "heist-iii": "Heist III",
    "identify-the-piece": "Identify the Piece",
    "imagine": "Imagine",
    "lost-category": "Lost Category",
    "m-guards-n-doors-and-k-choices": "M Guards:  N Doors:  and K Choices",
    "narcissism": "Narcissism",
    "once-upon-a-quote": "Barbie",
    "one-guard-screen": "One Guard:  Two Doors:  and a Screen",
    "opening-sequences": "Opening Sequences",
    "peanuts": "Peanuts",
    "piecemeal": "Piecemeal",
    "placeholder-i": "Placeholder I",
    "placeholder-ii": "Like Clockwork",
    "plagiarism": "Plagiarism",
    "red-blue": "Red Blue",
    "secret-ingredient": "Secret Ingredient",
    "six-degrees": "Six Degrees",
    "study-abroad": "Study Abroad",
    "ten-guards-ten-doors": "Ten Guards:  Ten Doors",
    "the-compact-disc": "The Compact Disc",
    "the-final-heist": "The Final Heist",
    "the-guard-and-the-door": "The Guard and The Door",
    "the-snack-zone": "The Snack Zone",
    "two-guards-river": "Two Guards:  Two Doors:  a Boat:  a River:  and a Cabbage",
    "two-guards-two-doors": "Two Guards:  Two Doors",
    "walk-of-fame": "Walk of Fame",
    "watching-between-the-lines": "Watching Between the Lines",
    "whats-my-ride": "What's My Ride?",
    "youve-got-this-covered": "You've Got This Covered"
}

ids = [
    "a-fistful-of-cards",
    "drop-the",
    "filming-schedule",
    "find-ben",
    "heist",
    "two-guards-two-doors",
    "walk-of-fame",
    "bluenos-puzzle-box",
    "boring-plot",
    "eye-of-the-storm",
    "eye-spy",
    "financial-crimes-3",
    "genetic-counseling",
    "identify-the-piece",
    "imagine",
    "m-guards-n-doors-and-k-choices",
    "narcissism",
    "once-upon-a-quote",
    "piecemeal",
    "the-snack-zone",
    "whats-my-ride",
    "a-fistful-of-cards-iv",
    "color-transfer",
    "constellation",
    "cutting-room-floor",
    "eye-to-eye",
    "fridge-magnets",
    "placeholder-i",
    "placeholder-ii",
    "red-blue",
    "secret-ingredient",
    "the-compact-disc",
    "the-final-heist",
    "the-guard-and-the-door",
    "balloon-animals",
    "fractal-shanty",
    "galileo-was-wrong",
    "peanuts",
    "plagiarism",
    "two-guards-river",
    "watching-between-the-lines",
    "example",
    "a-fistful-of-cards-ii",
    "aha-erlebnis",
    "beads",
    "heist-ii",
    "lost-category",
    "ten-guards-ten-doors",
    "youve-got-this-covered",
    "a-fistful-of-cards-iii",
    "are-you-sure",
    "chain-letters",
    "hand-letters",
    "heist-iii",
    "one-guard-screen",
    "opening-sequences",
    "six-degrees",
    "study-abroad"
]

for puzz_id in ids:
    print(id_to_name[puzz_id])